use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo::rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(
        out_dir.join("generated.rs"),
        r#"
pub fn message() -> &'static str {
    "generated by build script"
}

pub fn payload_len() -> usize {
    include_bytes!(concat!(env!("OUT_DIR"), "/payload.bin")).len()
}
"#,
    )
    .unwrap();
    // Large enough for archive overhead to be visible in timings without
    // making the end-to-end suite expensive.
    fs::write(out_dir.join("payload.bin"), vec![b'x'; 1024 * 1024]).unwrap();
}
